// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package structs

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register("struct", p)
}

var _ = adt.TopKind // in case the adt package isn't used

var p = &pkg.Package{
	Native: []*pkg.Builtin{{
		Name: "MinFields",
		Params: []pkg.Param{
			{Kind: adt.StructKind},
			{Kind: adt.IntKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			object, n := c.Struct(0), c.Int(1)
			if c.Do() {
				c.Ret, c.Err = MinFields(object, n)
			}
		},
	}, {
		Name: "MaxFields",
		Params: []pkg.Param{
			{Kind: adt.StructKind},
			{Kind: adt.IntKind},
		},
		Result: adt.BoolKind,
		Func: func(c *pkg.CallCtxt) {
			object, n := c.Struct(0), c.Int(1)
			if c.Do() {
				c.Ret, c.Err = MaxFields(object, n)
			}
		},
	}, {
		Name: "HasAttr",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.StringKind},
		},
		Result:      adt.TopKind,
		NonConcrete: true,
		Func: func(c *pkg.CallCtxt) {
			s, attrName := c.Schema(0), c.String(1)
			if c.Do() {
				c.Ret, c.Err = hasAttr(c.OpContext(), s, attrName)
			}
		},
	}, {
		Name: "FilterByAttr",
		Params: []pkg.Param{
			{Kind: adt.TopKind},
			{Kind: adt.StringKind},
			{Kind: adt.StringKind},
		},
		Result:      adt.TopKind,
		NonConcrete: true,
		Func: func(c *pkg.CallCtxt) {
			s, attrName, pattern := c.Schema(0), c.String(1), c.String(2)
			if c.Do() {
				c.Ret, c.Err = filterByAttr(c.OpContext(), s, attrName, pattern)
			}
		},
	}},
}
